# Generated by Django 3.2.6 on 2021-08-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'precios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('tienda', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
