# Generated by Django 3.2.6 on 2021-09-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='precios_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.BigIntegerField(db_column='precio')),
                ('fecha', models.DateTimeField(db_column='fecha')),
                ('id_producto', models.IntegerField(db_column='id_producto')),
                ('nombre', models.CharField(db_column='nombre', max_length=400)),
                ('tienda', models.CharField(db_column='tienda', max_length=400)),
                ('url', models.CharField(db_column='url', max_length=1000)),
            ],
            options={
                'db_table': 'precios_producto',
                'managed': False,
            },
        ),
    ]
