# Generated by Django 3.2.6 on 2021-09-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='correo', max_length=400, unique=True)),
                ('password', models.CharField(db_column='pass', max_length=400)),
            ],
            options={
                'db_table': 'personas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerPro',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.personas')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='product.productos')),
            ],
            options={
                'db_table': 'per_pro',
                'managed': True,
                'unique_together': {('id_persona', 'id_producto')},
            },
        ),
    ]
