# Generated by Django 3.2.6 on 2021-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='precios_productos_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(db_column='correo', max_length=400)),
                ('nombre', models.CharField(db_column='nombre', max_length=400)),
                ('precio', models.BigIntegerField(db_column='precio')),
            ],
            options={
                'db_table': 'precios_productos_cliente',
                'managed': False,
            },
        ),
    ]
